[font]
size = 12.0

[keyboard]
bindings = [
    {key = "Return", mods = "Control|Shift", action = "SpawnNewInstance"}
]

[window]
padding = { x = 10, y = 10}
dynamic_padding = true
opacity = 1.0

[scrolling]
history = 100000
